---
title: "Exploration of Qualitative Responses and Missing Data"
format: html
editor: visual
code-tools: TRUE
code-fold: TRUE
embed-resources: TRUE
params: 
  src_d: "../Code/R"
  data_d: "../Data"
  figs_d: "../PaperFigures"
  doc_freq_threshold: 4
---

# setup

```{r}
#| label: setup
#| include: FALSE

library("conflicted", quietly = TRUE)
library("magrittr", include.only = c("%<>%","%>%"),
        quietly = TRUE)
library("tidyverse", include.only = c() , quietly = TRUE)
library("gt",include.only=c(), quietly = TRUE)
library("broom",include.only=c(), quietly = TRUE)
library("patchwork",include.only=c(), quietly = TRUE)
library("labelled",include.only=c(), quietly = TRUE)
library("ggthemes",include.only=c(), quietly = TRUE)
library("ggpp",include.only=c(), quietly = TRUE)


ggplot2::theme_set( ggthemes::theme_fivethirtyeight())

response_complete.df <- readRDS(file.path(params[["data_d"]], 
                                                     "responses_final_complete_clean.rds"))
```

```{r}
#| label: fig data setup


scales.v <- c("Positivism", "Inclusivity", "Neutrality")
open_types.v <- c("OA","datashare","replication","prereg")
open_measure.v<- c("behavior", "behavior_binary", "opinion","b_percent_1","b_others_1", "b_when_1")
demos.v <- c("field", "field_first", "qualquant", "gender", "years")

oavars.v<- tidyr::crossing(open_types.v, open_measure.v) %>%
  dplyr::mutate(varname =glue::glue("{x}_{y}",x= open_types.v, y = open_measure.v) ) %>%
  pull(varname)

analysis_subset.df <-  
  response_complete.df %>% 
    dplyr::select(`ResponseId`, {{ scales.v }}, {{ oavars.v }}, {{ demos.v }} ) %>%
    dplyr::filter(!is.na(`field_first`))

analysis_subset_long.df <- 
  analysis_subset.df %>%
  tidyr::pivot_longer( cols = !c(`ResponseId`,`field`,`field_first`, `qualquant`, `gender`, {{scales.v}}, {{demos.v}})
                                 , names_to = c("type",".value"),
                       names_pattern ='(.+?)_(.*)') %>% 
  dplyr::mutate(behavior_binary_f = factor(behavior_binary, levels=c(0,1), labels=c("Not participated", "Participated")))

colnames(analysis_subset_long.df)
```

```{r}
#| label: ferg-1 type figure 


{analysis_subset_long.df %>%
  dplyr::filter(!is.na(opinion)) %>%
  ggplot2::ggplot() +
  ggplot2::aes(y=type, fill=opinion) +
  ggplot2::geom_bar( position = "fill") +
  theme(legend.position = "none")} /
{analysis_subset_long.df %>%
  dplyr::filter(!is.na(opinion)) %>%
  ggplot2::ggplot() +
  ggplot2::aes(y=type, fill=opinion) +
  ggplot2::geom_bar( position = "fill") +
  ggplot2::facet_wrap(vars(field_first))+
  ggplot2::labs(fill="") +
  ggplot2::theme(legend.position = "right", legend.direction="vertical")} + 
  patchwork::plot_annotation(title="OS Attitude by Field") -> 
  desc_fig1.plot

  desc_fig1.plot %>% 
    ggplot2::ggsave(plot=., 
          filename = file.path(params["figs_d"],"fig_A1_attitude_by_field.png"),
                    width=10, units = "in")

  desc_fig1.plot
```

```{r}
#| label: ferg-fig7-analogue
tmp<-
{analysis_subset_long.df %>%
  dplyr::filter(type %in% c("OA", "replication") ) %>%
  ggplot2::ggplot( aes(x = b_when_1 , color = type)) +
  ggplot2::stat_ecdf(geom = "line") +
  ggplot2::labs(y = "Cumulative percentage", x = "Year") +
  ggplot2::theme(legend.position = "none") } /
{analysis_subset_long.df %>%
  dplyr::filter(type %in% c("OA", "replication") ) %>%
  ggplot2::ggplot( aes(x = b_when_1 , color = type)) +
  ggplot2::stat_ecdf(geom = "line") +
  ggplot2::labs(y = "Cumulative percentage", x = "Year") + facet_wrap(vars(field_first))}  /
  {analysis_subset_long.df %>%
  dplyr::filter(type %in% c("OA", "replication"), 
                !is.na(qualquant)) %>%
  ggplot2::ggplot( aes(x = b_when_1 , color = type)) +
  ggplot2::stat_ecdf(geom = "line") +
  ggplot2::labs(y = "Cumulative percentage", x = "Year") + facet_wrap(vars(as.factor(qualquant))) } +
  patchwork::plot_annotation(title="First year of OA behavior") 



tmp %>% 
  ggplot2::ggsave(plot=., 
                  filename = file.path(params["figs_d"],"fig_a2_year_of_first_oa.png"),
                  width=10, units = "in")

tmp
```
