---
title: "Data Cleaning"
format: html
editor: visual
code-tools: TRUE
code-fold: TRUE
embed-resources: TRUE
params: 
  src_d: "../Code/R"
  data_d: "../Data"
  doc_freq_threshold: 4
---

# setup

```{r}
#| label: setup
#| include: FALSE

library("conflicted", quietly = TRUE)
library("magrittr", include.only = c("%<>%","%>%"),
        quietly = TRUE)
library("tidyverse", include.only = c() , quietly = TRUE)
library("gt",include.only=c(), quietly = TRUE)
library("broom",include.only=c(), quietly = TRUE)
library("patchwork",include.only=c(), quietly = TRUE)
library("labelled",include.only=c(), quietly = TRUE)
library("ggthemes",include.only=c(), quietly = TRUE)

ggplot2::theme_set( ggthemes::theme_fivethirtyeight())
```

# Clean data

```{r}
#| label: read-raw-data
qualtrics_file <- "Rhetorics_Qualtrics_260401.csv"

responses_raw.df <- readr::read_csv(
  file.path(params[["data_d"]], qualtrics_file ), 
            col_names=FALSE, skip=3, guess_max=Inf,                        
            show_col_types = FALSE

)

responses_labels.df <- readr::read_csv(
  file.path(params[["data_d"]], qualtrics_file ), 
            col_names=TRUE, skip=, guess_max=Inf, n_max=2,
            show_col_types = FALSE
)

names(responses_raw.df) <- names(responses_labels.df)

labelled::var_label(responses_raw.df) <- 
  dplyr::coalesce(
    responses_labels.df[1,] %>% t() %>% as.vector(),
    names(responses_raw.df)
    )

rm(responses_labels.df, qualtrics_file)
```

```{r}
#| label: clean-standardize

# merge with field labels

resp_ids.df <- 
  readr::read_csv(
  file.path(params[["data_d"]], "respondent_ids.csv" ), 
            col_names=TRUE, guess_max=Inf, 
            show_col_types = FALSE
)


resp_ids.df %<>%
  dplyr::mutate(field = dplyr::replace_values( field,
    'communication' ~ 'communications',
    'political' ~ 'political science'
  ),
    field = stringr::str_to_title(`field`)
  )

resp_ids.df %<>% group_by(ResponseId) %>%
  dplyr::summarize(field_multi = list(field), 
            email_multi = list(email_clean),
            field_first = head(field,1),
            .groups = "drop"
            )

responses_clean.df <- dplyr::left_join( 
  responses_raw.df,
  resp_ids.df ,
  by = "ResponseId")

responses_clean.df %<>%
  dplyr::mutate(dplyr::across(
              c(pos1:pos5, inc1:inc4, neut1:neut5),
              ~ factor( .x, 
                          ordered = TRUE,
                          levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"  )
                        )
  ))

# Recode opinion outcomes
opinion_vars <-
  c("datashare_opinion", "prereg_opinion", "OA_opinion", "replication_opinion")

responses_clean.df  %<>%
  dplyr::mutate(dplyr::across(dplyr::all_of(opinion_vars),
                ~ factor(
                  stringr::str_trim(.x),
                  ordered = TRUE,
                  levels = c( "Very much against", "Against", "Neither in favor nor against", "In favor", "Very much in favor")
                )))
                  

# Recode behavior outcomes
behavior_vars <- c("datashare_behavior", "prereg_behavior", "OA_behavior", "replication_behavior")

responses_clean.df  %<>%
  dplyr::mutate(dplyr::across(dplyr::all_of(behavior_vars),
                ~ factor(
                  stringr::str_trim(.x),
                  ordered = TRUE,
                  levels = c("No","Yes"))
  ))

responses_clean.df  %<>%
  dplyr::mutate(dplyr::across(c(`identifyResearch`, `identifyScience`),
                ~ factor(
                  stringr::str_trim(.x),
                  ordered = TRUE,
                  levels = c( "Not at all", "A little", "A moderate amount", "A lot", "A great deal")
                )
  ))

                 
responses_clean.df %<>%
  dplyr::mutate(
    discipline = as.factor(discipline),
    qualquant = as.factor(qualquant),
  )


# years sometimes had additional text, sometime mistaken for year started science
# extract /correct numeric val
responses_clean.df %<>%
  dplyr::mutate(
    years = as.numeric(stringr::str_extract(years,"\\d+")),
    years = ifelse (years < 1900, years, 2026-years),
  ) 

item_cols <- c(paste0("pos", 1:5), paste0("inc", 1:4), paste0("neut", 1:5))
outcome_cols <- c("datashare_opinion", "prereg_opinion", "OA_opinion", "replication_opinion",
                  "datashare_behavior", "prereg_behavior", "OA_behavior", "replication_behavior")


rev_5f <- function(x) { factor(6 - as.numeric(x), 
                          ordered = TRUE,
                          levels = 1:5,
                          labels  = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"  ))
 }


responses_clean.df  %<>%
  dplyr::mutate(
    # Inclusivity: Reverse-key 3 and 4
    inc3_r = rev_5f(inc3),
    inc4_r = rev_5f(inc4),
    # Neutrality: Reverse-key 1 and 3
    neut1_r = rev_5f(neut1),
    neut3_r = rev_5f(neut3)
  )


responses_clean.df %<>%
  dplyr::mutate(
    Positivism = rowMeans(  dplyr::across(dplyr::starts_with("pos"), 
                              ~ as.numeric(.x)), na.rm = TRUE),
    Inclusivity = rowMeans(dplyr::across( c( `inc1`, `inc2`, `inc3_r`, `inc4_r`),
                                           ~ as.numeric(.x))
                                          , na.rm = TRUE),
    Neutrality = rowMeans( dplyr::across (c(`neut1_r`, `neut2`, `neut3_r`, `neut4`, `neut5`), 
          ~ as.numeric(.x)),     na.rm = TRUE)
  )

rm(resp_ids.df)

```

```{r}
#| label: fix-typos-in-varnames
 colnames(responses_clean.df) %<>%
  stringr::str_replace("datasure","datashare") %>%
  stringr::str_replace('rep_','replication_')

responses_clean.df %<>%
  dplyr::rename(replication_b_percent_1=replication_b_percen_1 )

```

```{r}
#| label: code-non-unit-missing

# agree to participate : q54 yes
# filled out positivism scale

responses_clean.df %<>%
  dplyr::rowwise() %>%
  dplyr::mutate(
    unit_missing_INDICATOR = 
      any(c(is.na(dplyr::c_across(dplyr::starts_with("pos", ignore.case = FALSE))),
            (is.na(`Q54`)|`Q54`!='Yes'))),
    ) %>%
  dplyr::ungroup()

```

```{r}
#| label: substantive cleaning


# dummy  missing measures
responses_clean.df %<>% 
  dplyr::mutate(datashare_b_when_1=NA_real_, prereg_b_when_1=NA_real_) 

# respondents from multiple fields
responses_clean.df %<>% 
  dplyr::rowwise() %>%
  dplyr::mutate(n_fields = length(field_multi)) %>%
  dplyr::ungroup()%>%
  dplyr::mutate(field = ifelse(n_fields==1, field_first, "Multiple"))

responses_clean.df %<>%
  dplyr::mutate(years_clean = if_else(years > 80, NA_real_, years))
  


```

```{r}


scales.v <- c("Positivism", "Inclusivity", "Neutrality")
open_types.v <- c("OA","datashare","replication","prereg")
open_measure.v<- c("behavior","opinion","b_percent_1","b_others_1", "b_when_1")
demos.v <- c("field", "field_first", "qualquant", "gender", "years")

oavars.v<- tidyr::crossing(open_types.v, open_measure.v) %>%
  dplyr::mutate(varname =glue::glue("{x}_{y}",x= open_types.v, y = open_measure.v) ) %>%
  pull(varname)

oavars.v %>% stringr::str_extract('.*_when_.*') %>% na.omit()

tmp<- responses_clean.df %>% 
  dplyr::mutate(
    dplyr::across(oavars.v %>% stringr::str_extract('.*_when_.*') %>% na.omit(),
                  ~ years - (2025-.x),
                  .names = ".{col}_delta"))



# 1950 is default value ==> someone didn't answer the question
responses_clean.df %<>%
  dplyr::mutate(
    dplyr::across(oavars.v %>% stringr::str_extract('.*_when_.*') %>% na.omit(),
                  ~ na_if( .x, 1950))
  )

  
```

```{r}

field_order <- c(
  "Economics",
  "Business",
  "Political Science",
  "Psychology",
  "Communications",
  "Sociology",
  "Education",
  "Anthropology",
  "Multiple"
)

as_score <- function(x) {
  if (is.factor(x)) {
    as.numeric(x)
  } else {
    as.numeric(x)
  }
}

as_binary_yes <- function(x) {
  out <- case_when(
    as.character(x) == "Yes" ~ 1,
    as.character(x) == "No" ~ 0,
    TRUE ~ NA_real_
  )
  out
}

responses_clean.df %<>%
  mutate(
    field = factor(field, levels = field_order),
    field_first=factor(field_first, levels=field_order),
    qualquant = fct_drop(qualquant),
    across(
      c(
        datashare_opinion,
        prereg_opinion,
        OA_opinion,
        replication_opinion
      ),
      as_score,
      .names = "{.col}_score"
    ),
    across(
      c(
        datashare_behavior,
        prereg_behavior,
        OA_behavior,
        replication_behavior
      ),
      as_binary_yes,
      .names = "{.col}_binary"
    )
  )

```

```{r}
#| label: save-cleaned-file

responses_clean.df %>% 
  dplyr::count(`unit_missing_INDICATOR`)%>%
  gt::gt()

response_complete.df <- 
  responses_clean.df %>%
  dplyr::filter(!`unit_missing_INDICATOR`)

saveRDS(response_complete.df,
         file.path(params[["data_d"]],"responses_final_complete_clean.rds"))
```

```{r}
#| label: comment-analysis-hand-extract
# generate extract for hand-coding

comments_only.df <-
  response_complete.df %>%
  dplyr::select(`ResponseId`,`comments`)

comments_only.df %>% 
  dplyr::count(is.na(`comments`), sort=TRUE) %>%
  gt::gt()

comments_only.df %<>%
  dplyr::filter(!is.na(`comments`))

# for hand-coding

readr::write_excel_csv2(comments_only.df, delim='\t',
                        file.path(params[["data_d"]],"comments_export.tsv"))
```
