---
title: "Exploration of Qualitative Responses and Missing Data"
format: html
editor: visual
code-tools: TRUE
code-fold: TRUE
embed-resources: TRUE
params: 
  src_d: "../Code/R"
  data_d: "../Data"
  doc_freq_threshold: 4
---

# setup

```{r}
#| label: setup
#| include: FALSE

library("conflicted", quietly = TRUE)
library("magrittr", include.only = c("%<>%","%>%"),
        quietly = TRUE)
library("tidyverse", include.only = c() , quietly = TRUE)
library("gt",include.only=c(), quietly = TRUE)
library("broom",include.only=c(), quietly = TRUE)
library("patchwork",include.only=c(), quietly = TRUE)
library("labelled",include.only=c(), quietly = TRUE)
library("ggthemes",include.only=c(), quietly = TRUE)

ggplot2::theme_set( ggthemes::theme_fivethirtyeight())
```

# Clean data

```{r}
#| label: read-raw-data
qualtrics_file <- "Rhetorics_Qualtrics_260401.csv"

 file.path(params[["data_d"]], qualtrics_file )

responses_raw.df <- readr::read_csv(
  file.path(params[["data_d"]], qualtrics_file ), 
            col_names=FALSE, skip=3, guess_max=Inf,                        
            show_col_types = FALSE

)

responses_labels.df <- readr::read_csv(
  file.path(params[["data_d"]], qualtrics_file ), 
            col_names=TRUE, skip=, guess_max=Inf, n_max=2,
            show_col_types = FALSE
)

names(responses_raw.df) <- names(responses_labels.df)

labelled::var_label(responses_raw.df) <- 
  dplyr::coalesce(
    responses_labels.df[1,] %>% t() %>% as.vector(),
    names(responses_raw.df)
    )

rm(responses_labels.df, qualtrics_file)
```

```{r}
#| label: clean-standardize

# merge with field labels

resp_ids.df <- 
  readr::read_csv(
  file.path(params[["data_d"]], "respondent_ids.csv" ), 
            col_names=TRUE, guess_max=Inf, 
            show_col_types = FALSE
)


resp_ids.df %<>%
  dplyr::mutate(field = dplyr::replace_values( field,
    'communication' ~ 'communications',
    'political' ~ 'political science'
  ),
    field = stringr::str_to_title(`field`)
  )

resp_ids.df %<>% group_by(ResponseId) %>%
  summarize(field_multi = list(field), 
            email_multi = list(email_clean),
            field_first = head(field,1),
            .groups = "drop"
            )

responses_clean.df <- dplyr::left_join( 
  responses_raw.df,
  resp_ids.df ,
  by = "ResponseId")

responses_clean.df %<>%
  dplyr::mutate(dplyr::across(
              c(pos1:pos5, inc1:inc4, neut1:neut5),
              ~ factor( .x, 
                          ordered = TRUE,
                          levels = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"  )
                        )
  ))

# Recode opinion outcomes
opinion_vars <-
  c("datashare_opinion", "prereg_opinion", "OA_opinion", "replication_opinion")

responses_clean.df  %<>%
  dplyr::mutate(dplyr::across(dplyr::all_of(opinion_vars),
                ~ factor(
                  stringr::str_trim(.x),
                  ordered = TRUE,
                  levels = c( "Very much against", "Against", "Neither in favor nor against", "In favor", "Very much in favor")
                )))
                  

# Recode behavior outcomes
behavior_vars <- c("datashare_behavior", "prereg_behavior", "OA_behavior", "replication_behavior")

responses_clean.df  %<>%
  dplyr::mutate(dplyr::across(dplyr::all_of(behavior_vars),
                ~ factor(
                  stringr::str_trim(.x),
                  ordered = TRUE,
                  levels = c("No","Yes"))
  ))

responses_clean.df  %<>%
  dplyr::mutate(dplyr::across(c(`identifyResearch`, `identifyScience`),
                ~ factor(
                  stringr::str_trim(.x),
                  ordered = TRUE,
                  levels = c( "Not at all", "A little", "A moderate amount", "A lot", "A great deal")
                )
  ))

                 
responses_clean.df %<>%
  dplyr::mutate(
    discipline = as.factor(discipline),
    qualquant = as.factor(qualquant),
  )


# years sometimes had additional text, sometime mistaken for year started science
# extract /correct numeric val
responses_clean.df %<>%
  dplyr::mutate(
    years = as.numeric(stringr::str_extract(years,"\\d+")),
    years = ifelse (years < 1900, years, 2026-years),
  ) 

item_cols <- c(paste0("pos", 1:5), paste0("inc", 1:4), paste0("neut", 1:5))
outcome_cols <- c("datashare_opinion", "prereg_opinion", "OA_opinion", "replication_opinion",
                  "datashare_behavior", "prereg_behavior", "OA_behavior", "replication_behavior")


rev_5f <- function(x) { factor(6 - as.numeric(x), 
                          ordered = TRUE,
                          levels = 1:5,
                          labels  = c("Strongly disagree", "Somewhat disagree", "Neither agree nor disagree", "Somewhat agree", "Strongly agree"  ))
 }


responses_clean.df  %<>%
  dplyr::mutate(
    # Inclusivity: Reverse-key 3 and 4
    inc3_r = rev_5f(inc3),
    inc4_r = rev_5f(inc4),
    # Neutrality: Reverse-key 1 and 3
    neut1_r = rev_5f(neut1),
    neut3_r = rev_5f(neut3)
  )


# Reliability Checks (Cronbach's Alpha)
alpha_pos <-  
  responses_clean.df %>% 
  dplyr::select(starts_with("pos")) %>% 
  dplyr::mutate(dplyr::across(dplyr::everything(), 
                              ~ as.numeric(.x))) %>%
  psych::alpha()

alpha_pos
  
alpha_inc  <- 
    responses_clean.df %>% 
    dplyr::select(c(`inc1`, `inc2`, `inc3_r`, `inc4_r`)) %>% 
   dplyr::mutate(dplyr::across(dplyr::everything(), 
                              ~ as.numeric(.x))) %>%
    psych::alpha()
  
alpha_inc

alpha_neut  <- 
    responses_clean.df %>% 
    dplyr::select(c(`neut1_r`, `neut2`, `neut3_r`, `neut4`, `neut5`)) %>% 
   dplyr::mutate(dplyr::across(dplyr::everything(), 
                              ~ as.numeric(.x))) %>%
    psych::alpha()

alpha_neut


# Print Alphas
cat("Cronbach's Alpha Results:\n",
    "Positivism: ", round(alpha_pos$total$raw_alpha, 2), "\n",
    "Inclusivity:", round(alpha_inc$total$raw_alpha, 2), "\n",
    "Neutrality: ", round(alpha_neut$total$raw_alpha, 2), "\n")

responses_clean.df %<>%
  dplyr::mutate(
    Positivism = rowMeans(  dplyr::across(dplyr::starts_with("pos"), 
                              ~ as.numeric(.x)), na.rm = TRUE),
    Inclusivity = rowMeans(dplyr::across( c( `inc1`, `inc2`, `inc3_r`, `inc4_r`),
                                           ~ as.numeric(.x))
                                          , na.rm = TRUE),
    Neutrality = rowMeans( dplyr::across (c(`neut1_r`, `neut2`, `neut3_r`, `neut4`, `neut5`), 
          ~ as.numeric(.x)),     na.rm = TRUE)
  )

rm(opinion_vars, behavior_vars , rev_5, item_col, outcome_col, alpha_inc, alpha_neut, alpha_pos, resp_ids.df)

```

```{r}
#| label: code-non-unit-missing

# agree to participate : q54 yes
# filled out positivism scale

responses_clean.df %<>%
  dplyr::rowwise() %>%
  dplyr::mutate(
    unit_missing_INDICATOR = 
      any(c(is.na(dplyr::c_across(dplyr::starts_with("pos\\d"))),
            (is.na(`Q54`)|`Q54`!='Yes')))
  ) %>%
  dplyr::ungroup()


```

```{r}
#| label: save-cleaned-file

responses_clean.df %>% 
  dplyr::count(`unit_missing_INDICATOR`)%>%
  gt::gt()

response_complete.df <- 
  responses_clean.df %>%
  dplyr::filter(!`unit_missing_INDICATOR`)

saveRDS(response_complete.df,
         file.path(params[["data_d"]],"responses_final_complete_clean.rds"))
```

```{r}
#| label: comment-analysis-hand-extract
# generate extract for hand-coding

comments_only.df <-
  response_complete.df %>%
  dplyr::select(`ResponseId`,`comments`)

comments_only.df %>% 
  dplyr::count(is.na(`comments`), sort=TRUE) %>%
  gt::gt()

comments_only.df %<>%
  dplyr::filter(!is.na(`comments`))

# for hand-coding

readr::write_excel_csv2(comments_only.df, delim='\t',
                        file.path(params[["data_d"]],"comments_export.tsv"))
```

# ngram patterns

```{r}
#| label: comment-analysis-ngram

library("tidytext",include.only=c(), quietly = TRUE)


clean_text<-function(x) {
  x %>%  
    stringr::str_replace_all("U\\.S\\.","USA") %>% 
    stringr::str_to_lower() %>% 
    stringr::str_replace_all("[-\\)\\(\\&\"/]"," ") %>%
    stringr::str_replace_all("[^a-zA-Z \\.']", "")  %>% 
    stringr::str_squish()
}


comments_only.df %<>%
  dplyr::rowwise() %>%
  dplyr::mutate(comments_clean=clean_text(`comments`)) %>%
  dplyr::ungroup()

minimal_stopwords <-
  c("a",  "am", "an", "and", "any", "are", "aren't", "as", "at", "be","but", "by",  "did", "didn't", 
"do", "does", "doesn't", "doing", "don't", "down", "during", 
"each", "for", "from", "further", "had", "hadn't", "has", 
"hasn't", "have", "haven't", "having", "how", "i", "i'd", "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it", "it's", "its", "itself", "let's", "me", "my", "myself",  "of", "on",  "or", "other",  "so", "than", "that", "that's", "the","their", "they", "them", "then", "there", "there's", "these", "this", "how", "to", "too",  "was", "wasn't", "when", "when's", "where", "where's", "which", "while", "will", "with", "won't")


  
comment_ngram.df <-  comments_only.df %>%
  dplyr::select(`ResponseId`,`comments_clean`) %>%
  tidytext::unnest_tokens(ngram, `comments_clean`,
                token = "skip_ngrams", n = 3 ,k=1,
                stopwords=minimal_stopwords) %>%
  dplyr::mutate(ngram = stringr::str_squish(ngram)) %>% 
  dplyr::filter(str_length(ngram)>1)

ngram_freq.df <- comment_ngram.df %>% 
  dplyr::count(`ngram`,sort=TRUE) 

ngram_doc_freq.df <- 
  comment_ngram.df  %>%
  dplyr::distinct() %>% 
  dplyr::count(`ngram`, sort=TRUE)

comment_tf_idf <- 
  comment_ngram.df  %>% 
  dplyr::semi_join(
    ngram_doc_freq.df %>% dplyr::filter(n>params[["doc_freq_threshold"]]), 
    by = "ngram") %>%
  dplyr::count(`ngram`,`ResponseId`)%>%
  tidytext::bind_tf_idf(ngram, ResponseId, n)

```

```{r}
#| label: comment-analysis-plot

library("plotly",include.only=c(), quietly = TRUE)

{ngram_doc_freq.df %>% 
  dplyr::filter(n>params[["doc_freq_threshold"]]) %>% 
  ggplot2::ggplot(aes(x=fct_reorder(ngram,n),y=n))+
   geom_col() +
  coord_flip() +
  labs(x="terms occuring in multiple comments")} %>% plotly::ggplotly()

{ngram_doc_freq.df %>% 
  dplyr::filter(n>5 & stringr::str_detect(ngram," ")) %>% 
  ggplot2::ggplot(aes(x=fct_reorder(ngram,n),y=n))+
   geom_col() +
  coord_flip() +
  labs(x="terms occuring in multiple comments")} %>% plotly::ggplotly()

```

# Hand coded labels

```{r}
#| label: comment-hand-coded-analysis

hand_coded.df <- readr::read_csv(
                        file.path(params[["data_d"]],"comments_hand_coded - main.csv"))

hand_coded.df %<>% 
  dplyr::mutate(dplyr::across(dplyr::everything(), ~tidyr::replace_na(.x, "")))

{ hand_coded.df %>% 
  dplyr::select(-`ResponseId`, -`comments`) %>%
  tidyr::pivot_longer(cols=dplyr::everything()) %>%
  dplyr::mutate(name=ifelse(stringr::str_starts(name,"topic"),"topic", name)) %>%
  dplyr::count(`name`,`value`) %>%
  dplyr::filter(value!="") %>% 
  ggplot2::ggplot() + 
  ggplot2::aes(x=`name`, y=`n`, fill=`value` ) +
  ggplot2::geom_bar(stat="identity", position="stack") +
  ggplot2::coord_flip() 
  } %>% plotly::ggplotly()
   
```

# Missing Data

```{r}
#| label: missing-data-analysis
library("naniar",include.only=c(), quietly = TRUE)
library("mice",include.only=c(), quietly = TRUE)
library("visdat",include.only=c(), quietly = TRUE)
library("skimr",include.only=c(), quietly = TRUE)
```

```{r}
response_complete.df %>% 
  dplyr::slice_sample(n=10) %>%
  dplyr::glimpse() 
```

```{r}
response_complete.df %>% 
  skimr::skim() 
```
